# Generated by Django 6.0.5 on 2026-05-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_doctor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SHOP_OWNER', 'Shop Owner'), ('RESTAURANT_OWNER', 'Restaurant Owner'), ('DRIVER', 'Driver'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
