# Generated by Hand on 2026-05-17 19:54

from django.db import migrations

def populate_categories(apps, schema_editor):
    Category = apps.get_model('shops', 'Category')
    categories = [
        "خضروات وفواكه",
        "ألبان وأجبان",
        "لحوم ودواجن",
        "مخبوزات وحلويات",
        "بقالة وسوبرماركت",
        "مشروبات وعصائر",
        "منظفات وعناية شخصية",
        "صيدلية وأدوية",
        "أخرى"
    ]
    for cat_name in categories:
        Category.objects.get_or_create(name=cat_name)

def remove_categories(apps, schema_editor):
    Category = apps.get_model('shops', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_product_quantity'),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_code=remove_categories),
    ]
