# Generated by Django 6.0.5 on 2026-05-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid_to_shop',
            field=models.BooleanField(default=False),
        ),
    ]
