# Generated by Django 6.0.5 on 2026-05-18 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_customer_otp_order_dispute_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SHOP_OWNER', 'Shop Owner')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_received_ratings', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_ratings', to='orders.order')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_given_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('order', 'rater', 'rater_type')},
            },
        ),
    ]
