# Generated by Django 6.0.5 on 2026-05-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_driverrating'),
        ('shops', '0007_shop_closing_time_shop_opening_time_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_orders', to='shops.shop'),
        ),
    ]
