# Generated by Django 6.0.5 on 2026-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_picked_up_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('ON_DELIVERY', 'On Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('PENDING_RETURN', 'Pending Return')], default='PENDING', max_length=20),
        ),
    ]
