# Generated by Django 6.0.5 on 2026-05-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_shops',
            field=models.TextField(blank=True, default=''),
        ),
    ]
