# Generated by Django 6.0.5 on 2026-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_paid_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_otps',
            field=models.TextField(blank=True, default=''),
        ),
    ]
