# Generated by Django 6.0.5 on 2026-05-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_shop_otps'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postponed_shops',
            field=models.TextField(blank=True, default=''),
        ),
    ]
